import AppKit
import Combine

final class MouseScrollDirectionManager: ObservableObject {

    private weak var settings: AppSettings?
    private var cancellables = Set<AnyCancellable>()

    private var eventTap: CFMachPort?
    private var runLoopSource: CFRunLoopSource?

    // Prevent injected event recursion
    private let injectedEventTag: Int64 = 0x4153525652

    init(settings: AppSettings) {
        self.settings = settings

        settings.$mouseScrollDirectionReversed
            .receive(on: RunLoop.main)
            .sink { [weak self] enabled in
                enabled ? self?.start() : self?.stop()
            }
            .store(in: &cancellables)

        if settings.mouseScrollDirectionReversed {
            start()
        }
    }

    deinit {
        stop()
    }

    static var isAccessibilityTrusted: Bool {
        AXIsProcessTrusted()
    }

    static func requestAccessibilityPermission() {
        let options = [
            kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true
        ] as CFDictionary

        AXIsProcessTrustedWithOptions(options)
    }


    private func start() {

        guard eventTap == nil else {
            return
        }

        let mask = CGEventMask(
            1 << CGEventType.scrollWheel.rawValue
        )

        let callback: CGEventTapCallBack = {
            _, type, event, userInfo in

            guard let userInfo else {
                return Unmanaged.passUnretained(event)
            }

            let manager =
            Unmanaged<MouseScrollDirectionManager>
                .fromOpaque(userInfo)
                .takeUnretainedValue()

            return manager.handle(
                type: type,
                event: event
            )
        }


        guard let tap = CGEvent.tapCreate(
            tap: .cgSessionEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: mask,
            callback: callback,
            userInfo: Unmanaged.passUnretained(self).toOpaque()
        ) else {
            Self.requestAccessibilityPermission()
            return
        }


        guard let source = CFMachPortCreateRunLoopSource(
            kCFAllocatorDefault,
            tap,
            0
        ) else {
            CFMachPortInvalidate(tap)
            return
        }


        eventTap = tap
        runLoopSource = source

        CFRunLoopAddSource(
            CFRunLoopGetMain(),
            source,
            .commonModes
        )

        CGEvent.tapEnable(
            tap: tap,
            enable: true
        )
    }


    private func stop() {

        if let source = runLoopSource {
            CFRunLoopRemoveSource(
                CFRunLoopGetMain(),
                source,
                .commonModes
            )
        }

        if let tap = eventTap {
            CFMachPortInvalidate(tap)
        }

        eventTap = nil
        runLoopSource = nil
    }


    private func handle(
        type: CGEventType,
        event: CGEvent
    ) -> Unmanaged<CGEvent>? {


        guard type == .scrollWheel else {
            return Unmanaged.passUnretained(event)
        }


        // Ignore events generated by ourselves
        if event.getIntegerValueField(
            .eventSourceUserData
        ) == injectedEventTag {

            return Unmanaged.passUnretained(event)
        }


        guard settings?.mouseScrollDirectionReversed == true
        else {
            return Unmanaged.passUnretained(event)
        }


        let phase = event.getIntegerValueField(
            .scrollWheelEventScrollPhase
        )

        let momentum = event.getIntegerValueField(
            .scrollWheelEventMomentumPhase
        )


        // Keep trackpad untouched for now
        if phase != 0 || momentum != 0 {
            return Unmanaged.passUnretained(event)
        }


        guard settings?.mouseScrollReversesVertical == true
        else {
            return Unmanaged.passUnretained(event)
        }


        let value = event.getIntegerValueField(
            .scrollWheelEventPointDeltaAxis1
        )


        guard value != 0 else {
            return Unmanaged.passUnretained(event)
        }


        let reversed = Int32(-value)


        guard let newEvent = CGEvent(
            scrollWheelEvent2Source: nil,
            units: .pixel,
            wheelCount: 1,
            wheel1: reversed,
            wheel2: 0,
            wheel3: 0
        ) else {
            return Unmanaged.passUnretained(event)
        }


        newEvent.setIntegerValueField(
            .eventSourceUserData,
            value: injectedEventTag
        )


        newEvent.post(
            tap: .cghidEventTap
        )


        return nil
    }
}
